### PR TITLE
Map RA Service wrappers completed

### PR DESCRIPTION
**Pull request by SummaNetworks**
Added implementation for MAPServiceBase.acivate, deactivate, addMAPServiceListener and removeMAPServiceListener methods in all serviceWrappers of MAP ra.

### CODE REVIEW

**Comment by vetss** [comment]
Hi @SummaNetworks,

MAPServiceBase.acivate, deactivate, addMAPServiceListener and removeMAPServiceListener methods are not managable by MAP RA users level. 

They are invoked from MAPResourceAdaptor.raActive() and raInactive() and that is why it is forbidden to invoke them from MAP RA users level (from wrappers like MAPServiceSmsWrapper).

Can you please explain the use case whan you need to use such updated wrappers ?

**Comment by SummaNetworks** [comment]
Hi,

I am trying to invoke sendXxxRequest from an sbb. As I have not found an example about how to do it, I have taken the functional tests of map as example. In these tests the client implementation calls to acivate() before sending the request, and the RA throws the UnsupportedException when I call it.  Is it unnecessary to call this method? 

Thank you un advance.

**Comment by abhayani** [comment]
RA does that when it starts and it activates all the services. So no need
to do that explicitly from SBB.

Amit

**Comment by vetss** [comment]
For an example of how to use RA inside SBB you can check this:
https://github.com/RestComm/camelgateway/blob/master/core/slee/sbbs/src/main/java/org/restcomm/camelgateway/slee/CamelGatewaySbb.java

This is CAP RA but idea is the same.

**Comment by vetss** [comment]
I am marking the PR as closed as we do not need it.

**Pull request closed without merging**
