### PR TITLE
ISUP RA update

### PR DESCRIPTION
**Pull request by georgeyanev**
Introduce CircuitActivity type - call session and maintenance

### CODE REVIEW

**Comment by vetss** [comment]
Hello,

thanks for your update. Can you please shortly describe what your update solve, which bug or which enchansment. This is needed to understand how the update will affect code.
Thanks.

**Comment by vetss** [comment]
Hello @georgeyanev,

may I ask you again to describe which issues does your update cover so we will be able to accept it.
Thanks.

**Comment by georgeyanev** [comment]
Hello @vetss, 
actually the change is about introducing a means for distinguish the purpose of the circuit activity - whether is for maintenance (with reset, block messages etc.) or regular (call session messages).
Feel free to accept or reject the changes as you appraise.

**Comment by vetss** [comment]
Hello @georgeyanev 

I have added your updates into netty-2 branch.
We have stopped of adding of commits into master branch because we will release soon. We will rename netty-2 branch to master soon.

Thanks for your work.

**Pull request closed without merging**
